---
kind: Service
apiVersion: v1
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  ports:
    - name: html-openshift-app
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: html-openshift-app
---
kind: Service
apiVersion: v1
metadata:
  name: html-openshift-app-database
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  ports:
    - name: html-openshift-app-database
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: html-openshift-app-database


#change name
label app
label part of

image 
port